# Generated by Django 5.0.6 on 2024-06-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("mot_de_passe", models.CharField(max_length=100)),
                ("date_de_naissance", models.DateField()),
                ("date_inscription", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
