# Generated by Django 5.0.6 on 2024-06-19 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Produits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("quantite", models.IntegerField(default=1)),
                ("price", models.FloatField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("judo", "Judo"),
                            ("boxe", "Boxe"),
                            ("football", "Football"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Commandes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("judo", "Judo"),
                            ("boxe", "Boxe"),
                            ("football", "Football"),
                        ],
                        max_length=50,
                    ),
                ),
                ("commande_ok", models.BooleanField(default=False)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommandeArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField(default=1)),
                ("price", models.FloatField(default=0.0)),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.commandes",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.produits"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_commande", models.IntegerField(default=1)),
                ("commander", models.BooleanField(default=False)),
                ("date_commande", models.DateTimeField(auto_now_add=True)),
                ("total", models.FloatField(default=0.0)),
                ("utilisateur", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ("commandes", models.ManyToManyField(to="store.commandes")),
            ],
        ),
        migrations.AddField(
            model_name="commandes",
            name="produits",
            field=models.ManyToManyField(
                through="store.CommandeArticle", to="store.produits"
            ),
        ),
    ]
