# Generated by Django 5.0.6 on 2024-06-17 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_commande", models.CharField(max_length=100)),
                ("commander", models.BooleanField(default=False)),
                ("date_commande", models.DateTimeField(auto_now_add=True)),
                (
                    "commandes_boxe",
                    models.ManyToManyField(to="store.commande_boxe_produit"),
                ),
                (
                    "commandes_football",
                    models.ManyToManyField(to="store.commande_football_produit"),
                ),
                ("commandes_judo", models.ManyToManyField(to="store.commande_judo")),
                (
                    "utilisateur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
