# Generated by Django 5.0.6 on 2024-06-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="numero_commande",
            field=models.IntegerField(default=1),
        ),
    ]
