# Generated by Django 5.0.6 on 2024-06-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_remove_cart_utilisateur_cart_utilisateur"),
    ]

    operations = [
        migrations.AddField(
            model_name="commandes",
            name="total",
            field=models.FloatField(default=0.0),
        ),
    ]
