# Generated by Django 5.0.6 on 2024-06-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_produit_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Boxe_produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("price", models.FloatField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
            ],
        ),
    ]
