# Generated by Django 5.0.6 on 2024-06-17 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_cart_numero_commande"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Produits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("price", models.FloatField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("judo", "Judo"),
                            ("boxe", "Boxe"),
                            ("football", "Football"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="commande_boxe_produit",
            name="produit",
        ),
        migrations.RemoveField(
            model_name="commande_boxe_produit",
            name="utilisateur",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="commandes_boxe",
        ),
        migrations.RemoveField(
            model_name="commande_football_produit",
            name="produit",
        ),
        migrations.RemoveField(
            model_name="commande_football_produit",
            name="utilisateur",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="commandes_football",
        ),
        migrations.RemoveField(
            model_name="commande_judo",
            name="produit",
        ),
        migrations.RemoveField(
            model_name="commande_judo",
            name="utilisateur",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="commandes_judo",
        ),
        migrations.CreateModel(
            name="Commandes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.IntegerField(default=1)),
                ("commande", models.BooleanField(default=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("judo", "Judo"),
                            ("boxe", "Boxe"),
                            ("football", "Football"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.produits"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cart",
            name="commandes",
            field=models.ManyToManyField(to="store.commandes"),
        ),
        migrations.DeleteModel(
            name="Boxe_produit",
        ),
        migrations.DeleteModel(
            name="commande_boxe_produit",
        ),
        migrations.DeleteModel(
            name="Football_produit",
        ),
        migrations.DeleteModel(
            name="commande_football_produit",
        ),
        migrations.DeleteModel(
            name="Produit",
        ),
        migrations.DeleteModel(
            name="commande_judo",
        ),
    ]
