# Generated by Django 5.0.6 on 2024-06-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_produits_remove_commande_boxe_produit_produit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produits",
            name="quantite",
            field=models.IntegerField(default=1),
        ),
    ]
