# Generated by Django 5.0.6 on 2024-06-18 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_produits_quantite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commandes",
            name="commande",
        ),
        migrations.RemoveField(
            model_name="commandes",
            name="produit",
        ),
        migrations.RemoveField(
            model_name="commandes",
            name="quantite",
        ),
        migrations.CreateModel(
            name="CommandeArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField(default=1)),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.commandes",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.produits"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="commandes",
            name="produits",
            field=models.ManyToManyField(
                through="store.CommandeArticle", to="store.produits"
            ),
        ),
    ]
