# Generated by Django 5.0.6 on 2024-06-18 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_remove_commandes_commande_remove_commandes_produit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commandes",
            name="produit",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commandes_produit",
                to="store.produits",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="commandes",
            name="produits",
            field=models.ManyToManyField(
                related_name="commandes_produits",
                through="store.CommandeArticle",
                to="store.produits",
            ),
        ),
    ]
