# Generated by Django 5.0.6 on 2024-06-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_commandes_produit_alter_commandes_produits"),
    ]

    operations = [
        migrations.AddField(
            model_name="commandes",
            name="commande",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="commandes",
            name="quantite",
            field=models.IntegerField(default=1),
        ),
    ]
