# Generated by Django 5.0.6 on 2024-06-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_commandearticle_utilisateur"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commandearticle",
            name="utilisateur",
        ),
    ]
