# Generated by Django 5.0.6 on 2024-06-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_remove_commandearticle_utilisateur"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commandes",
            name="commande",
        ),
        migrations.RemoveField(
            model_name="commandes",
            name="produit",
        ),
        migrations.RemoveField(
            model_name="commandes",
            name="quantite",
        ),
        migrations.AlterField(
            model_name="commandes",
            name="produits",
            field=models.ManyToManyField(
                through="store.CommandeArticle", to="store.produits"
            ),
        ),
    ]
